In [1]:
import numpy as np
import cv2

이름, 행렬의 깊이(단일 색상 값의 크기), 채널(RGB, BGR, gray scale), mat_type 출력

In [ ]:
def print_matInfo(name, image):
    if image.dtype == 'uint8': mat_type = 'CV_8U'
    elif image.dtype == 'int8': mat_type = 'CV_8S'
    elif image.dtype == 'int16': mat_type = 'CV_16S'
    elif image.dtype == 'float32': mat_type = 'CV_32F'
    elif image.dtype == 'float64': mat_type = 'CV_64F'
    nchannel = 3 if image.ndim == 3 else 1

    print("%12s: depth(%s), channels(%s) -> mat_type(%sC%d)"
            % (name, image.dtype, nchannel, mat_type, nchannel))

컬러 이미지를 그레이 스케일 그리고 컬러로 불러오기

In [ ]:
title1, title2 = 'color2gray', 'color2color'
color2gray = cv2.imread("../images/timetable.jpg", cv2.IMREAD_GRAYSCALE)
color2color = cv2.imread("../images/timetable.jpg", cv2.IMREAD_COLOR)

if color2gray is None or color2color is None : 
    raise Exception("영상 파일 읽기 에러")

print("행렬 좌표 (100, 100) 화소값")
print("%s %s"  % (title1, color2gray[100, 100]))
print("%s %s"  % (title2, color2color[100, 100]))

print_matInfo(title1, color2gray)
print_matInfo(title2, color2color)

cv2.imshow(title1, color2gray)
cv2.imshow(title2, color2color)
cv2.waitKey(0)

행렬 좌표 (100, 100) 화소값
color2gray 163
color2color [117 135 236]
  color2gray: depth(uint8), channels(1) -> mat_type(CV_8UC1)
 color2color: depth(uint8), channels(3) -> mat_type(CV_8UC3)


113

: 

지정하지 않고 불러오기

In [ ]:
title3 = 'unchagned'
color2unchanged = cv2.imread("../images/timetable.tif", cv2.IMREAD_UNCHANGED)
if color2unchanged is None:
    raise Exception("영상 파일 읽기 에러")

print("영상 행렬 좌표 (10, 10) 화소값")
print(title3, '원소 자료형', type(color2unchanged[10][10][0])) 
print(title3, '화소값(3원소)', type(color2unchanged[10, 10]))
print_matInfo(title3, color2unchanged)

영상 행렬 좌표 (10, 10) 화소값
unchagned 원소 자료형 <class 'numpy.uint8'>
unchagned 화소값(3원소) <class 'numpy.ndarray'>
   unchagned: depth(uint8), channels(3) -> mat_type(CV_8UC3)


[ WARN:0@208.628] global grfmt_tiff.cpp:122 TIFF_Warning TIFFReadDirectory: Unknown field with tag 42112 (0xa480) encountered


여러 형식과 화질 지정, 압축 레벨 지정, 다른 형식으로 저장 해보기

In [ ]:
img = cv2.imread("images/timetable.jpg", cv2.IMREAD_GRAYSCALE)
if img is None: raise Exception("영상 파일 읽기 에러")

params_jpg = (cv2.IMWRITE_JPEG_QUALITY, 10)
params_png = [cv2.IMWRITE_PNG_COMPRESSION, 9]

cv2.imwrite("../images/write_test1.jpg", img)
cv2.imwrite("../images/write_test2.jpg", img, params_jpg)
cv2.imwrite("../images/write_test3.png", img, params_png)
cv2.imwrite("../images/write_test4.bmp", img)
print("저장 완료")

저장 완료


In [ ]:
img8 = cv2.imread("images/timetable.jpg", cv2.IMREAD_COLOR)
if img is None: raise Exception("영상 파일 읽기 에러")

# uint16에서 65535만큼 표현하므로 255로 나누고 그 수를 곱하여 변환 하는거다 그리고 저 연산은 행렬에 스칼라 곱하는거다
img16 = np.uint16(img8 * (65535 / 255)) 
# float32은 0.0 ~ 1.0 만큼 표현하므로 저 수를 곱한다.
img32 = np.float32(img8 * (1/255))

print("img8 행렬의 일부\n %s\n"  % img8[10:12, 10:13])
print("img16 행렬의 일부\n %s\n" % img16[10:12, 10:13])
print("img32 행렬의 일부\n %s\n" % img32[10:12, 10:13])

cv2.imwrite("../images/write_test_16.tif", img16)
cv2.imwrite("../images/write_test_32.tif", img32)

img8 행렬의 일부
 [[[255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]]]

img16 행렬의 일부
 [[[65535 65535 65535]
  [65535 65535 65535]
  [65535 65535 65535]]

 [[65535 65535 65535]
  [65535 65535 65535]
  [65535 65535 65535]]]

img32 행렬의 일부
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]



True